on:
  workflow_run: 
    workflows: ["build_artifacts"]
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - main
      - develop

jobs:
  chatgptjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(process.env.OPENAI_API_KEY);
            fetch('https://api.openai.com/v1/completions', { data: JSON.stringify({
                  "model": "text-davinci-003",
                  "prompt": "write unit test cases for following javascript code \nconst getRandomKey = () => {\n  return `${new Date().getTime()}${Math.ceil(Math.random()*100000)}`;\n}\n\n//Test Case 1\nit('should return random key', () => {\n  expect(typeof getRandomKey()).toBe('string');\n});\n\n//Test Case 2\nit('should have time component', () => {\n  expect(getRandomKey().includes(new Date().getTime().toString())).toBeTruthy();\n});\n\n//Test Case 3\nit('should have random component', () => {\n  expect(getRandomKey().includes(Math.ceil(Math.random()*100000).toString())).toBeTruthy();\n});",
                  "temperature": 0.71,
                  "max_tokens": 4000,
                  "top_p": 1,
                  "frequency_penalty": 0,
                  "presence_penalty": 0
                }), method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization':  'Bearer ${process.env.OPENAI_API_KEY}' });
