# This is a basic workflow to help you get started with Actions

name: test-generation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ self-hosted ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      
      - name: list the files
        run: ls -a
        
      - name: print the default python version
        run: python -V
      
      - name: print the python version
        run: python3 -V
      
      - name: install python dependencies
        run: 
          python3 -m pip install -r requirements.txt
          
      - name: generate test cases
        env:
          OPENAPI_KEY: ${{secrets.OPENAI_API_KEY}}
          GIT_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GIT_PR_ID: ${{github.event.number}}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python3 generate_testcase.py
