on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  bundle_artifacts_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Generating tests
        uses: actions/checkout@v3
      - run: mkdir -p path/to/artifact
      - run: echo hello1 > path/to/artifact/test_file1.txt
      - run: echo hello2 > path/to/artifact/test_file2.txt
      - run: echo ${{github.run_id}}
      
      - name: Tar test files
        run: tar -cvf ${{github.event.number}}_tests.tar path/to/artifact

      - name: Upload test files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{github.event.number}}-testcases-artifact
          path: ${{github.event.number}}_tests.tar
          
      - name: Notify the PR owner
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.run_id}},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == '${{github.event.number}}-testcases-artifact'
            })[0];
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: matchArtifact.archive_download_url
            })
