on:
  workflow_run: 
    workflows: ["build_artifacts"]
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - main
      - develop

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(process.env);
