on:
  workflow_run: 
    workflows: ["build_artifacts"]
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - main
      - develop

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
           console.log(JSON.stringify(context.repo));
           var workflows = await github.rest.actions.listWorkflowRunsForRepo({
                       owner: context.repo.owner,
                       repo: context.repo.repo,
                       branch: 'patch-1',
                       per_page: 100,
                       status: 'success'
                    });
                console.log(JSON.stringify(workflows.data.workflow_runs.map(workflow => `${workflow.workflow_id}-${workflow.actor.login}-${workflow.id}`)));
         
