on:
  workflow_run: 
    workflows: ["build_artifacts"]
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - main
      - develop

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
           console.log(`${context.payload.sender.login}-${context.payload.pull_request.head.ref}`);
           var workflows = await github.rest.actions.listWorkflowRunsForRepo({
                       owner: context.repo.owner,
                       repo: context.repo.repo,
                       branch: context.payload.pull_request.head.ref,
                       per_page: 100,
                       status: 'success',
                       actor: context.payload.sender.login
                    });
                console.log(JSON.stringify(workflows.data.workflow_runs.map(workflow => `${workflow.workflow_id}-${workflow.actor.login}-${workflow.id}`)));
         
