on:
  workflow_run: 
    workflows: ["build_artifacts"]
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - main
      - develop

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
           var workflows = await github.rest.actions.listWorkflowRunsForRepo({
                       owner: context.repo.owner,
                       repo: context.repo.repo,
                       branch: context.payload.pull_request.head.ref,
                       per_page: 100,
                       actor: context.payload.sender.login
                    });
            const filtered = workflows.data.workflow_runs.filter(workflow => workflow.name === 'build_artifacts');
            console.log(`${filtered[0].id}-${filtered[0].status}`);
            console.log(JSON.stringify(workflows.data.workflow_runs.map(workflow => `${workflow.name}-${workflow.actor.login}-${workflow.id}`)));
         
