# This is a basic workflow to help you get started with Actions
name: test-generation
# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout the current repo code
        uses: actions/checkout@v3
        
      - name: checkout the genie tools
        uses: actions/checkout@v3
        with:
            repository: bm-repo/genie-tool
            token: ${{secrets.GTOKEN}}
            path: tools
            
      - name: list all the files
        run: ls -a
      
      - name: install python dependencies
        run: 
          python3 -m pip install -r tools/requirements.txt
          
      - name: generate test cases
        env:
          OPENAPI_KEY: ${{secrets.OPENAI_API_KEY}}
          GIT_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GIT_PR_ID: ${{github.event.number}}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python3 tools/generate_testcase.py
        
      - name: check tg folder contents
        run: ls -lrt ./test-genie
        
      - name: Tar test files
        run: tar -cvf testgenie_tests_${{github.event.number}}.tar test-genie

      - name: Upload test files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: testcases-artifact-${{github.event.number}}
          path: testgenie_tests_${{github.event.number}}.tar
